### ISSUE TITLE
Fix build.py tag names for Dependabot PRs

### ISSUE THREAD

**Issue by alexpdp7** [alexpdp7/zqxjkcrud#476]
They use not allowed characters.

```
> (None) $ podman build . --build-arg QUAY_EXPIRES_AFTER=3d -t zqxjkcrud:dependabot/maven/us.fatehi-schemacrawler-16.20.1
Error: tag zqxjkcrud:dependabot/maven/us.fatehi-schemacrawler-16.20.1: invalid reference format
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/zqxjkcrud/zqxjkcrud/build.py", line 28, in build_images_and_push
    _run(["podman", "build", ".", "--build-arg", f"QUAY_EXPIRES_AFTER={quay_expires_after}", "-t", f"zqxjkcrud:{tag}"])
  File "/home/runner/work/zqxjkcrud/zqxjkcrud/build.py", line 8, in _run
    return subprocess.run(cmd, **kwargs, check=check, cwd=cwd)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'build', '.', '--build-arg', 'QUAY_EXPIRES_AFTER=3d', '-t', 'zqxjkcrud:dependabot/maven/us.fatehi-schemacrawler-16.20.1']' returned non-zero exit status 125.
Error: Process completed with exit code 1.
```

**Comment by alexpdp7** [comment]
Was fixed in https://github.com/alexpdp7/zqxjkcrud/commit/90a3eb85ddbdf944a79cf5c1ca13e88b85acdd8e .
